// DOM element references
export const DOM = {
    searchForm: document.getElementById('search-form'),
    cityInput: document.getElementById('city-input'),
    locationBtn: document.getElementById('location-btn'),
    langSwitchBtn: document.getElementById('lang-switch-btn'),
    historyContainer: document.getElementById('search-history'),
    loading: document.getElementById('loading'),
    errorMessage: document.getElementById('error-message'),
    weatherResult: document.getElementById('weather-result'),
    cityName: document.getElementById('city-name'),
    temperature: document.getElementById('temperature'),
    weatherCondition: document.getElementById('weather-condition'),
    weatherIcon: document.getElementById('weather-icon'),
    lastUpdated: document.getElementById('last-updated'),
    unitToggle: document.getElementById('unit-toggle'),
    hourlyContainer: document.getElementById('hourly-container'),
    
    // Weather metrics widgets
    apparentTemp: document.getElementById('apparent-temp'),
    uvIndex: document.getElementById('uv-index'),
    rainChance: document.getElementById('rain-chance'),
    windSpeed: document.getElementById('wind-speed'),
    
    // Sun rise/set metrics
    sunriseTime: document.getElementById('sunrise-time'),
    sunsetTime: document.getElementById('sunset-time'),
    map: document.getElementById('map')
};

// Weather condition icon mappings (WMO codes)
export const weatherIcons = {
    0: 'fa-sun',
    1: 'fa-cloud-sun',
    2: 'fa-cloud-sun',
    3: 'fa-cloud',
    45: 'fa-smog',
    48: 'fa-smog',
    51: 'fa-cloud-rain',
    53: 'fa-cloud-rain',
    55: 'fa-cloud-rain',
    61: 'fa-cloud-showers-heavy',
    63: 'fa-cloud-showers-heavy',
    65: 'fa-cloud-showers-heavy',
    71: 'fa-snowflake',
    73: 'fa-snowflake',
    75: 'fa-snowflake',
    80: 'fa-cloud-showers-heavy',
    81: 'fa-cloud-showers-heavy',
    82: 'fa-cloud-showers-heavy',
    95: 'fa-cloud-bolt'
};

// Weather condition descriptions for all supported languages
export const weatherDescriptions = {
    bg: {
        0: 'Ясно небе',
        1: 'Предимно ясно',
        2: 'Частична облачност',
        3: 'Облачно',
        45: 'Мъгла',
        48: 'Скреж на мъгла',
        51: 'Лек ръмеж',
        53: 'Умерен ръмеж',
        55: 'Интензивен ръмеж',
        61: 'Лек дъжд',
        63: 'Умерен дъжд',
        65: 'Силен дъжд',
        71: 'Лек снеговалеж',
        73: 'Умерен снеговалеж',
        75: 'Силен снеговалеж',
        80: 'Леки превалявания',
        81: 'Умерени превалявания',
        82: 'Силни превалявания',
        95: 'Гръмотевична буря'
    },
    en: {
        0: 'Clear sky',
        1: 'Mostly clear',
        2: 'Partly cloudy',
        3: 'Cloudy',
        45: 'Fog',
        48: 'Fog with rime',
        51: 'Light drizzle',
        53: 'Moderate drizzle',
        55: 'Heavy drizzle',
        61: 'Light rain',
        63: 'Moderate rain',
        65: 'Heavy rain',
        71: 'Light snow',
        73: 'Moderate snow',
        75: 'Heavy snow',
        80: 'Light showers',
        81: 'Moderate showers',
        82: 'Heavy showers',
        95: 'Thunderstorm'
    },
    de: {
        0: 'Klarer Himmel',
        1: 'Überwiegend klar',
        2: 'Teilweise bewölkt',
        3: 'Bewölkt',
        45: 'Nebel',
        48: 'Nebel mit Reif',
        51: 'Leichter Niesel',
        53: 'Mäßiger Niesel',
        55: 'Intensiver Niesel',
        61: 'Leichter Regen',
        63: 'Mäßiger Regen',
        65: 'Intensiver Regen',
        71: 'Leichte Schneefälle',
        73: 'Mäßige Schneefälle',
        75: 'Intensive Schneefälle',
        80: 'Leichte Schauer',
        81: 'Mäßige Schauer',
        82: 'Intensive Schauer',
        95: 'Gewitter'
    },
    sk: {
        0: 'Čisté nebo',
        1: 'Väčšinou jasno',
        2: 'Čiastočne zamračené',
        3: 'Zamračené',
        45: 'Hmla',
        48: 'Hmla s ľadom',
        51: 'Slabá rosa',
        53: 'Mierna rosa',
        55: 'Silná rosa',
        61: 'Slabý dážď',
        63: 'Mierny dážď',
        65: 'Silný dážď',
        71: 'Slabý sneh',
        73: 'Mierny sneh',
        75: 'Silný sneh',
        80: 'Slabé prehánky',
        81: 'Mierné prehánky',
        82: 'Silné prehánky',
        95: 'Búrka'
    }
};

// Multi-language translations for UI elements
export const translations = {
    bg: {
        title: "Прогноза за времето",
        placeholder: "Въведете град на английски...",
        search: "Търси",
        feelsLike: "Усеща се като",
        uvIndex: "UV Индекс",
        rainChance: "Шанс за дъжд",
        wind: "Вятър",
        sunrise: "Изгрев",
        sunset: "Залез",
        toggle: "Към °F",
        loading: "Зареждане...",
        riskLow: "Нисък", riskMed: "Умерен", riskHigh: "Висок",
        updated: "Последно обновяване",
        cityNotFound: "Городът не е намерен.",
        fetchError: "Грешка при извличане на данни за времето",
        locationDenied: "Достъпът до локация бе отказан.",
        geoNotSupported: "Геолокацията не се поддържа от вашия браузър."
    },
    en: {
        title: "Weather Forecast",
        placeholder: "Enter city in English...",
        search: "Search",
        feelsLike: "Feels like",
        uvIndex: "UV Index",
        rainChance: "Rain chance",
        wind: "Wind",
        sunrise: "Sunrise",
        sunset: "Sunset",
        toggle: "To °F",
        loading: "Loading...",
        riskLow: "Low", riskMed: "Moderate", riskHigh: "High",
        updated: "Last updated",
        cityNotFound: "City not found.",
        fetchError: "Error fetching weather data",
        locationDenied: "Location access denied.",
        geoNotSupported: "Geolocation is not supported by your browser."
    },
    de: {
        title: "Wettervorhersage",
        placeholder: "Stadt auf Englisch eingeben...",
        search: "Suchen",
        feelsLike: "Gefühlt wie",
        uvIndex: "UV-Index",
        rainChance: "Regenwahrscheinlichkeit",
        wind: "Wind",
        sunrise: "Sonnenaufgang",
        sunset: "Sonnenuntergang",
        toggle: "Zu °F",
        loading: "Laden...",
        riskLow: "Niedrig", riskMed: "Mäßig", riskHigh: "Hoch",
        updated: "Zuletzt aktualisiert",
        cityNotFound: "Stadt nicht gefunden.",
        fetchError: "Fehler beim Abrufen von Wetterdaten",
        locationDenied: "Standortzugriff verweigert.",
        geoNotSupported: "Geolokalisierung wird von Ihrem Browser nicht unterstützt."
    },
    sk: {
        title: "Predpoveď počasia",
        placeholder: "Zadajte mesto v angličtine...",
        search: "Hľadať",
        feelsLike: "Pocitová teplota",
        uvIndex: "UV Index",
        rainChance: "Šanca na dážď",
        wind: "Vietor",
        sunrise: "Východ slnka",
        sunset: "Západ slnka",
        toggle: "Na °F",
        loading: "Načítavam...",
        riskLow: "Nízky", riskMed: "Mierny", riskHigh: "Vysoký",
        updated: "Posledná aktualizácia",
        cityNotFound: "Mesto sa nenašlo.",
        fetchError: "Chyba pri získavaní údajov o počasí",
        locationDenied: "Prístup k polohe bol zamietnutý.",
        geoNotSupported: "Geolokácia nie je podporovaná vašim prehliadačom."
    }
};